version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'resns_app'
      MYSQL_USER: 'resns'
      MYSQL_PASSWORD: 'resns'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql/init:/docker-entrypoint-initdb.d
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_ARBITRARY: 1
#      PMA_HOSTS: mysql
#      PMA_USER: root
#      PMA_PASSWORD: miraiketai2020_admin
#    ports:
#      - 8080:80

